// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnfajhdfcjhhpozsngbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZmFqaGRmY2poaHBvenNuZ2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTU3ODAsImV4cCI6MjA2NTgzMTc4MH0.H9ogq8H3Isdd0WAx9gsQ13DDnerIZTcIfGuvUPlqQkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);